### PR TITLE
Convert http://www.Amazon.com → httpS://Smile.Amazon.com

### PR DESCRIPTION
**Pull request by TPS**
@MagicUsTwo:

To publicize [AmazonSmile](https://smile.amazon.com/gp/help/customer/display.html?nodeId=201365340), which may be worthwhile, @ least ½%.  😀🤷🏾‍♂️

Also, might as well increase link security while I'm here.  🙇🏾‍♂️

What d'y'all think?

### CODE REVIEW

**Comment by nhysi** [comment]
Hi there !
There is an [eligibility criteria](https://smile.amazon.com/gp/help/customer/display.html?nodeId=201365340) that appears not to apply to android applications.

Besides that, switching to HTTPS is a good idea.

**Comment by TPS** [comment]
@nhysi That's true: that's why I said it's to publicise the program, rather than support it, in view of Ida's Dream.

**Comment by nhysi** [comment]
@TPS So there is also an Amazon link in MV1 to edit. (which is neither HTTPS) 😃

**Comment by TPS** [comment]
@nhysi Already included that 😜

**Comment by TPS** [comment]
Ping @magicustwo What do you think?

**Comment by magicustwo** [comment]
Nice idea! Especially the more secure links (how did I miss that? 😅)

Thanks!

**Comment by TPS** [comment]
You're welcome! & thanks for my 2 favorite mobile games! :bow:

**Pull request merged**
